### ISSUE TITLE
about sandbox

### ISSUE THREAD

**Issue by kangyao-kk** [AllanAscencio/ebay-pipeline#4]
Hello, during the development process, eBay's sandbox seems to be unavailable, and I can't register a seller account for the sandbox. Can you help me?

**Comment by AllanAscencio** [comment]
Hello, the seller account I used was a normal ebay account for selling, and regarding sandbox, keep in mind the pipeline was created only using the production key-set, I didn't use sandbox APIs in the pipeline, if you want to use sandbox, you will have to update all the APIs to sandbox changing the urls.
